
  CREATE TABLE "AM"."ASSETBYUSER" 
   (	"USERCOMPNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERPERSONALID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"USERSERVICEUNIT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ASSETNUMBER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ASSETIP" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ADDDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "ASSETBYUSER_PK" PRIMARY KEY ("ASSETNUMBER", "ASSETIP", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "AM"."ASSETBYUSER"."USERCOMPNAME" IS 'Nombre completo del usuario';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."USERNAME" IS 'Nombre de usuario de active directory';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."USERPERSONALID" IS 'Numero de cedula';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."USERSERVICEUNIT" IS 'Unidad de servicios';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."ASSETNUMBER" IS 'Numero de actvo';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."ASSETIP" IS 'Ip de activo';
   COMMENT ON COLUMN "AM"."ASSETBYUSER"."ADDDATE" IS 'Fecha de ingreso de registro de usuario, ip y numero de activo';
   COMMENT ON TABLE "AM"."ASSETBYUSER"  IS 'Contiene registros de usuarios con direccion IP mas numero de activo';
