//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ASSETBYUSER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ASSETBYUSER()
    {
        this.ASSETMOVEMENTs = new HashSet<ASSETMOVEMENT>();
    }

    public string USERCOMPNAME { get; set; }
    public string USERNAME { get; set; }
    public string USERPERSONALID { get; set; }
    public string EmployeeERVICEUNIT { get; set; }
    public string ASSETNUMBER { get; set; }
    public string ASSETIP { get; set; }
    public System.DateTime ADDDATE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ASSETMOVEMENT> ASSETMOVEMENTs { get; set; }
}

public partial class ASSETMOVEMENT
{
    public decimal MOVEMENTID { get; set; }
    public string ASSETNUMBER { get; set; }
    public string ASSETIP { get; set; }
    public string USERNAME { get; set; }
    public string MOVEMENTTYPE { get; set; }
    public string ACCESORIESDETAIL { get; set; }
    public string MOVEMENTREASON { get; set; }
    public System.DateTime MOVEMENTDATE { get; set; }

    public virtual ASSETBYUSER ASSETBYUSER { get; set; }
}
