//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMovementBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETBYUSER
    {
        public string USERCOMPNAME { get; set; }
        public string USERNAME { get; set; }
        public string USERPERSONALID { get; set; }
        public string USERSERVICEUNIT { get; set; }
        public string ASSETNUMBER { get; set; }
        public string ASSETIP { get; set; }
        public System.DateTime ADDDATE { get; set; }
    }
}
