//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMovementBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETBYUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSETBYUSER()
        {
            this.ASSETMOVEMENTs = new HashSet<ASSETMOVEMENT>();
        }
    
        public string USERCOMPNAME { get; set; }
        public string USERNAME { get; set; }
        public string USERPERSONALID { get; set; }
        public string USERSERVICEUNIT { get; set; }
        public string ASSETNUMBER { get; set; }
        public string ASSETIP { get; set; }
        public System.DateTime ADDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETMOVEMENT> ASSETMOVEMENTs { get; set; }
    }
}
