//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMovementBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETMOVEMENT
    {
        public decimal MOVEMENTID { get; set; }
        public string ASSETNUMBER { get; set; }
        public string ASSETIP { get; set; }
        public string USERNAME { get; set; }
        public string MOVEMENTTYPE { get; set; }
        public string ACCESORIESDETAIL { get; set; }
        public string MOVEMENTREASON { get; set; }
        public System.DateTime MOVEMENTDATE { get; set; }
    }
}
