//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMovementBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETMOVEMENT
    {
        public decimal MOVEMENTID { get; set; }
        public string ASSETNUMBER { get; set; }
        public string ASSETIP { get; set; }
        public string USERNAME { get; set; }
        public string MOVEMENTTYPE { get; set; }
        public string ACCESORIESDETAIL { get; set; }
        public string MOVEMENTREASON { get; set; }
        public System.DateTime MOVEMENTDATE { get; set; }
    
        public virtual ASSETBYUSER ASSETBYUSER { get; set; }
    }
}
